name: multi-disease-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pandas=2.0.3
  - numpy=1.24.3
  - scikit-learn=1.3.0
  - xgboost=1.7.6
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - plotly=5.15.0
  - streamlit=1.25.0
  - joblib=1.3.2
  - requests=2.31.0
  - pytest=7.4.0
  - pytest-cov=4.1.0
  - jupyter=1.0.0
  - ipykernel=6.25.0
  - tqdm=4.65.0
  - pip:
    - shap==0.42.1
    - imbalanced-learn==0.11.0 